version: '2'
services:
    website:
        # build: ./php
        image: reliefsupports/webserver:0.1
        volumes:
            - ../:/var/www/html
        links:
            - db:db-server
        ports:
            - "8080:80"
        depends_on:
            - db

    db:
        image: mariadb
        volumes:
            - ./db/initdb:/docker-entrypoint-initdb.d
        ports:
            - "3312:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: flood
            MYSQL_USER: reliefuser
            MYSQL_PASSWORD: reliefpwd
